### ISSUE TITLE
Properly handle stock split

### ISSUE THREAD

**Issue by StockwatchDev** [StockwatchDev/stockwatch#27]
**[Original report](https://bitbucket.org/stockwatch-ws/stockwatch/issue/21) by Theo de Vries (Bitbucket: [theojadevries](https://bitbucket.org/theojadevries), GitHub: [tjadevries](https://github.com/tjadevries)).**

----------------------------------------

In my portfolio, I have one stock split. This situation is not dealt with properly.

**Comment by tjadevries** [comment]
In my portfolio the stock split is now handled correctly.
